#!/bin/bash

# Get all staged C/C++ files that are added, copied, or modified
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp|h|c)$')

if [ -n "$STAGED_FILES" ]; then
  for FILE in $STAGED_FILES; do
    clang-format-19 -i "$FILE"
    git add "$FILE"
  done
fi

exit 0